// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20190613141856_initialize-ContactApiDb")]
    partial class initializeContactApiDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.ContactUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("HomePhone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("MiddleName");

                    b.Property<string>("Mobile")
                        .IsRequired();

                    b.Property<DateTime?>("Modified");

                    b.Property<string>("WorkPhone");

                    b.HasKey("Id");

                    b.ToTable("ContactUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 6, 13, 9, 18, 56, 265, DateTimeKind.Local).AddTicks(3597),
                            Email = "fred@revature.com",
                            FirstName = "Fred",
                            LastName = "Belotte",
                            Mobile = "9876543212"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2019, 6, 13, 9, 18, 56, 266, DateTimeKind.Local).AddTicks(6006),
                            Email = "carol.baxtor@revature.com",
                            FirstName = "Carol",
                            LastName = "Baxtor",
                            Mobile = "9234567876"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
